# Generated by Django 2.0.1 on 2018-01-24 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='Cvs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('entrepriseName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('entreprisePassword', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('sinNumber', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('personName', models.CharField(max_length=100)),
                ('personPassword', models.CharField(max_length=40)),
                ('isInEntrepriseName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=80)),
                ('postalCode', models.CharField(max_length=6)),
                ('sexe', models.CharField(max_length=1)),
                ('personEmail', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('sinNumberPersonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordFlag', models.BooleanField(default=False)),
                ('sinNumberPersonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='cv',
            name='sinNumberPersonne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Person'),
        ),
    ]
