# Generated by Django 2.0.1 on 2018-01-24 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180124_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='personName',
            new_name='Person_Name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='personPassword',
            new_name='Person_Password',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='sinNumber',
            new_name='SIN_Number',
        ),
    ]
