# Generated by Django 2.0.1 on 2018-01-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180124_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Person_Password',
            field=models.CharField(max_length=500),
        ),
    ]
