# Generated by Django 2.0.1 on 2018-01-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180125_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='sinNumberPersonne',
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='entreprisePassword',
            field=models.CharField(max_length=200),
        ),
    ]
