# Generated by Django 2.0.1 on 2018-01-29 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180129_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrepriseNameRequests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Entreprise')),
                ('personSINRequests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Person')),
            ],
        ),
    ]
