# Generated by Django 2.0.1 on 2018-01-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_entreprise_jobname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='jobName',
        ),
        migrations.AddField(
            model_name='requests',
            name='jobName',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
