# Generated by Django 2.0.1 on 2018-01-30 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180129_1404'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cv',
        ),
        migrations.AlterField(
            model_name='person',
            name='isInEntrepriseName',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to='polls.Entreprise'),
        ),
    ]
