# Generated by Django 2.0.1 on 2018-01-30 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180130_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='isInEntrepriseName',
            field=models.ForeignKey(default='Nonee', on_delete=django.db.models.deletion.SET_DEFAULT, to='polls.Entreprise'),
        ),
    ]
