# Generated by Django 2.0.1 on 2018-01-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20180130_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformations',
            name='phone',
            field=models.CharField(max_length=14),
        ),
    ]
